name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
    FILENAME: ""
    PACKAGENAME: ""

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create Release JSON
        run: python3 tools/get_hex_files.py
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            board_release.json
            tmp/*
      
      - name: Clear folder
        run: rm -r tmp